from openai import OpenAI
import json

client = OpenAI()

tools = [
    {
        "type":"function",
        "name":"get_horoscope",
        "description":"Get today's horoscope for an astrological sign",
        "parameters":{
            "type":"object",
            "properties":{
                "sign":{
                    "type":"string",
                    "description":"An astrological sign like Taurus or Aquarius"
                },
            },
            "required":["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

input_list = [
    {"role":"user","content":"What is my Horoscope . I am capricorn"}
]

response = client.responses.create(
    model='gpt-4o-mini',
    tools=tools,
    input=input_list
)

input_list += response.output

for item in response.output:
    if item.type == "function_call":
        horoscope  = get_horoscope(json.loads(item.arguments))

        input_list.append({
            "type":"function_call_output",
            "call_id":item.call_id,
            "output":json.dumps({
                "horoscope":horoscope
            })
        })


print("Final input:")
print(input_list)


response = client.responses.create(
    model='gpt-4o-mini',
    instructions="Respond only with a horoscope generated by a tool",
    tools=tools,
    input=input_list
)



print("Final Output:")
print(response.model_dump_json(indent=2))
print("\n"+response.output_text)